"""Add tables

Revision ID: 97cfd2ae0eb1
Revises:
Create Date: 2024-02-09 15:59:01.619659

"""

from collections.abc import Sequence
from typing import Union

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97cfd2ae0eb1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS alertswisscap")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cap_alerts",
        sa.Column("cap_id", sa.String(), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("cap_sender", sa.String(), nullable=True),
        sa.Column("cap_sent", sa.DateTime(), nullable=False),
        sa.Column("cap_status", sa.String(), nullable=False),
        sa.Column("cap_message_type", sa.String(), nullable=False),
        sa.Column("cap_scope", sa.String(), nullable=False),
        sa.Column("cap_code", sa.String(), nullable=True),
        sa.Column("cap_restriction", sa.String(), nullable=True),
        sa.Column("cap_references", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("cap_id"),
        schema="alertswisscap",
    )
    op.create_table(
        "cap_info",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cap_language", sa.String(), nullable=True),
        sa.Column("cap_category", sa.String(), nullable=False),
        sa.Column("cap_event", sa.String(), nullable=False),
        sa.Column("cap_urgency", sa.String(), nullable=False),
        sa.Column("cap_severity", sa.String(), nullable=False),
        sa.Column("cap_certainty", sa.String(), nullable=False),
        sa.Column("cap_onset", sa.DateTime(), nullable=True),
        sa.Column("cap_sender_name", sa.String(), nullable=True),
        sa.Column("cap_expires", sa.DateTime(), nullable=True),
        sa.Column("cap_headline", sa.String(), nullable=False),
        sa.Column("cap_description", sa.String(), nullable=True),
        sa.Column("cap_instruction", sa.String(), nullable=True),
        sa.Column("cap_web", sa.String(), nullable=True),
        sa.Column("cap_contact", sa.String(), nullable=True),
        sa.Column("cap_alert_cap_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cap_alert_cap_id"], ["alertswisscap.cap_alerts.cap_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cap_alert_cap_id", "cap_language", name="uc_cap_info_cap_id_cap_languange"),
        schema="alertswisscap",
    )
    op.create_table(
        "cap_areas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cap_area_desc", sa.String(), nullable=True),
        sa.Column("cap_area_altitude", sa.Float(), nullable=True),
        sa.Column("cap_area_ceiling", sa.Float(), nullable=True),
        sa.Column("cap_info_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["cap_info_id"], ["alertswisscap.cap_info.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="alertswisscap",
    )
    op.create_table(
        "cap_circles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.Column("radius", sa.Float(), nullable=True),
        sa.Column("cap_area_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["cap_area_id"], ["alertswisscap.cap_areas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="alertswisscap",
    )
    op.create_table(
        "cap_geocodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("valueName", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("cap_area_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["cap_area_id"], ["alertswisscap.cap_areas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="alertswisscap",
    )
    op.create_table(
        "cap_polygons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.Column("cap_area_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["cap_area_id"], ["alertswisscap.cap_areas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="alertswisscap",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_cap_polygons_geom", table_name="cap_polygons", schema="alertswisscap", postgresql_using="gist"
    )
    op.drop_table("cap_polygons", schema="alertswisscap")
    op.drop_table("cap_geocodes", schema="alertswisscap")
    op.drop_index(
        "idx_cap_circles_geom", table_name="cap_circles", schema="alertswisscap", postgresql_using="gist"
    )
    op.drop_table("cap_circles", schema="alertswisscap")
    op.drop_table("cap_areas", schema="alertswisscap")
    op.drop_table("cap_info", schema="alertswisscap")
    op.drop_table("cap_alerts", schema="alertswisscap")
    # ### end Alembic commands ###
