"""Create schema

Revision ID: c8314aa90324
Revises: dcd953748674
Create Date: 2025-04-29 08:38:30.342377

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8314aa90324"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS alertswisscap;")


def downgrade() -> None:
    op.execute("DROP SCHEMA alertswisscap CASCADE;")
