"""initial

Revision ID: cc756c5eec19
Revises: 
Create Date: 2023-11-23 14:38:24.694503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc756c5eec19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cap_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('cap_id', sa.String(), nullable=False),
    sa.Column('cap_sender', sa.String(), nullable=False),
    sa.Column('cap_sent', sa.DateTime(), nullable=False),
    sa.Column('cap_status', sa.String(), nullable=False),
    sa.Column('cap_message_type', sa.String(), nullable=False),
    sa.Column('cap_scope', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cap_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cap_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cap_language', sa.String(), nullable=False),
    sa.Column('cap_category', sa.String(), nullable=True),
    sa.Column('cap_event', sa.String(), nullable=True),
    sa.Column('cap_urgency', sa.String(), nullable=True),
    sa.Column('cap_severity', sa.String(), nullable=True),
    sa.Column('cap_certainty', sa.String(), nullable=True),
    sa.Column('cap_onset', sa.DateTime(), nullable=True),
    sa.Column('cap_sender_name', sa.String(), nullable=True),
    sa.Column('cap_headline', sa.String(), nullable=True),
    sa.Column('cap_description', sa.String(), nullable=True),
    sa.Column('cap_instruction', sa.String(), nullable=True),
    sa.Column('cap_contact', sa.String(), nullable=True),
    sa.Column('cap_alert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cap_alert_id'], ['cap_alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cap_info')
    op.drop_table('cap_areas')
    op.drop_table('cap_alerts')
    # ### end Alembic commands ###
